# Generated by Django 5.2.4 on 2025-09-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('verified', 'Verified User'), ('non_verified', 'Non-Verified User')], default='non_verified', max_length=20),
        ),
    ]
