# Generated by Django 5.2.4 on 2025-07-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_tag_capstonepaper_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonepaper',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
