# Generated by Django 5.2.4 on 2025-09-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstonepaper',
            old_name='adviser',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='capstonepaper',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='capstonepaper',
            name='status',
        ),
    ]
