# Generated by Django 5.2.4 on 2025-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_capstonepaper_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('adviser', 'Adviser'), ('verified', 'Verified User'), ('non_verified', 'Non-Verified User')], default='non_verified', max_length=20),
        ),
    ]
