# Generated by Django 5.2.4 on 2025-10-05 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paperaccessrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperaccessrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paperaccessrequest',
            index=models.Index(fields=['status'], name='core_papera_status_a38d39_idx'),
        ),
        migrations.AddIndex(
            model_name='paperaccessrequest',
            index=models.Index(fields=['paper', 'status'], name='core_papera_paper_i_a725ba_idx'),
        ),
        migrations.AddIndex(
            model_name='paperaccessrequest',
            index=models.Index(fields=['expires_at'], name='core_papera_expires_dfb795_idx'),
        ),
    ]
