# Generated by Django 5.2.4 on 2025-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_can_upload_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonepaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revise', 'Revise')], default='pending', max_length=10),
        ),
    ]
