# Generated by Django 5.2.4 on 2025-10-05 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paperaccessrequest_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paperaccessrequest',
            name='core_papera_paper_i_a725ba_idx',
        ),
        migrations.AddIndex(
            model_name='paperaccessrequest',
            index=models.Index(fields=['user', 'paper'], name='core_papera_user_id_2b341a_idx'),
        ),
    ]
