# Generated by Django 5.2.4 on 2025-10-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_paperaccessrequest_core_papera_paper_i_a725ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonepaper',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
