# Generated by Django 5.2.4 on 2025-07-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_capstonepaper_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstonepaper',
            name='adviser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
