# Generated by Django 5.2.4 on 2025-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_capstonepaper_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capstonepaper',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
