# Generated by Django 5.2.4 on 2025-12-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_capstonepaper_avatar_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstonepaper',
            old_name='instructor',
            new_name='adviser',
        ),
    ]
