# Generated by Django 5.2.4 on 2025-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paperaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonepaper',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
