# Generated by Django 5.2.4 on 2025-12-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_instructor_capstonepaper_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('password_reset', 'Password Reset'), ('role_changed', 'Role Changed'), ('paper_uploaded', 'Paper Uploaded'), ('paper_edited', 'Paper Edited'), ('paper_deleted', 'Paper Deleted'), ('paper_viewed', 'Paper Viewed'), ('access_granted', 'Access Granted'), ('access_denied', 'Access Denied'), ('upload_permission_changed', 'Upload Permission Changed'), ('support_request', 'Support Request')], max_length=50),
        ),
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.AlterField(
            model_name='capstonepaper',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adviser'),
        ),
    ]
