# Generated by Django 5.2.4 on 2025-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_capstonepaper_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstonepaper',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
