# Generated by Django 5.2.4 on 2026-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_action_adviser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstonepaper',
            name='file',
            field=models.FileField(max_length=255, upload_to='capstone_pdfs/'),
        ),
    ]
