# Generated by Django 5.2.4 on 2025-08-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250804_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstonepaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revise', 'Revise')], default='pending', max_length=10),
        ),
    ]
