# Generated by Django 5.2.4 on 2025-08-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ay', models.CharField(db_index=True, max_length=9)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='core.capstonepaper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ay'], name='core_paperv_ay_6003da_idx'), models.Index(fields=['paper', 'ay'], name='core_paperv_paper_i_357dc2_idx')],
            },
        ),
    ]
